export const blogsData = [
  {
    author_id: "17",
    author_name: "rishika@29",
    category: "tech",
    content:
      "Embark on a cosmic odyssey as we unravel the mysteries of black holes. From their formation to the mind-bending phenomena within, this blog explores the gravitational wonders that shape our universe.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 3,
    input: "Journey Through the Cosmos: Unraveling Black Holes",
    number_comments: 0,
    number_likes: 0,
    number_saves: 1,
    number_views: 0,
  },
  {
    author_id: "17",
    author_name: "rishika@29",
    category: "tech",
    content:
      "Dive into the world of mindful coding, where each line of code becomes a meditation. Explore techniques to enhance focus, reduce errors, and create code that not only runs smoothly but also reflects the essence of mindfulness",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 4,
    input: "The Art of Mindful Coding",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239447780",
    author_name: "saumya16",
    category: "ai",
    content:
      "Trace the evolution of artificial intelligence from its humble beginnings to the sophisticated algorithms of today. Peek into the future possibilities and ethical considerations that AI presents.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 5,
    input: "The Evolution of Artificial Intelligence: Past, Present, Future",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239447780",
    author_name: "saumya16",
    category: "product",
    content:
      "Discover the principles and strategies that drive successful product design. From user-centric approaches to iterative prototyping, this blog explores the key elements that contribute to creating innovative and user-friendly products.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 6,
    input: "Innovation Unveiled: The Secrets Behind Successful Product Design",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239479204",
    author_name: "Aman.33",
    category: "education",
    content:
      "Take a sneak peek into the future of technology. This blog discusses emerging technologies such as AI, quantum computing, and blockchain, forecasting their potential impact on various industries.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 7,
    input: "Emerging Technologies 2024: A Glimpse into the Future",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239479204",
    author_name: "Aman.33",
    category: "api",
    content:
      "Stay ahead of the curve by exploring the latest trends and techniques in web development. From progressive web apps to serverless architecture, this blog provides insights into the evolving landscape of web development.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 8,
    input: "Mastering Modern Web Development: Trends and Techniques",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239533751",
    author_name: "tanmay.bhat",
    category: "uiux",
    content:
      "Elevate your web design skills by mastering CSS animations. This blog guides you through the art of creating captivating animations that enhance user engagement and bring your websites to life.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 9,
    input: "Unveiling CSS magic",
    number_comments: 0,
    number_likes: 0,
    number_saves: 1,
    number_views: 0,
  },
  {
    author_id: "1708239562299",
    author_name: "random.varun",
    category: "uiux",
    content:
      "Delve into the principles of user-centric design and human-centered UX. Learn how understanding user behavior, empathy, and usability testing contribute to creating seamless and delightful user experiences.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 11,
    input: "User-Centric Design: Elevating Experiences with Human-Centered UX",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239505016",
    author_name: "techie@1",
    category: "education",
    content:
      "Uncover the benefits of experiential learning in education. This blog explores hands-on approaches, internships, and real-world experiences that enhance traditional classroom learning.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 12,
    input:
      "Beyond the Classroom: The Role of Experiential Learning in Education",
    number_comments: 0,
    number_likes: 0,
    number_saves: 0,
    number_views: 0,
  },
  {
    author_id: "1708239533751",
    author_name: "tanmay.bhat",
    category: "uiux",
    content:
      "Embrace the practice of mindfulness in daily life. This blog offers practical tips on incorporating mindfulness into routines, fostering gratitude, and finding joy in the present moment.",
    display: true,
    done: false,
    duemonth: 1,
    dueyear: 2024,
    file: "",
    id: 10,
    input: "Mindful Living: Cultivating Happiness in Everyday Moments",
    number_comments: 0,
    number_likes: 1,
    number_saves: 0,
    number_views: 0,
  },
];

export const usersData = [
  {
    id: "17",
    name: "rishika@29",
    email: "rishika@gmail.com",
    password: "123",
    dob: "11/11/1111",
    number_followers: 0,
    number_following: 0,
    plan_id: 3,
    views: 0,
  },
  {
    cPassword: "1234",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239189287,
    name: "rishika",
    number_followers: 0,
    number_following: 0,
    password: "1234",
    plan: "Diamond(10 blogs a day) - $10",
    plan_id: 10,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239271861,
    name: "rishika@2912",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan: "Diamond(10 blogs a day) - $10",
    plan_id: 10,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239447780,
    name: "saumya16",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan: "Diamond(10 blogs a day) - $10",
    plan_id: 10,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239479204,
    name: "Aman.33",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan: "Diamond(10 blogs a day) - $10",
    plan_id: 10,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239505016,
    name: "techie@1",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan_id: 0,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239533751,
    name: "tanmay.bhat",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan: "Diamond(10 blogs a day) - $10",
    plan_id: 10,
    views: 0,
  },
  {
    cPassword: "123",
    dob: "1111-11-11",
    email: "rishikamandhyan@gmail.com",
    id: 1708239562299,
    name: "random.varun",
    number_followers: 0,
    number_following: 0,
    password: "123",
    plan: "Gold(5 blogs a day) - $5",
    plan_id: 5,
    views: 0,
  },
];
